# Generated by Django 5.0.6 on 2024-06-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddnscamera',
            name='stream_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staticcamera',
            name='stream_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
